version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user123:simplepass0000@db:5432/awfulDB
  db:
    build: ./db
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=simplepass0000
      - POSTGRES_DB=awfulDB
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: